config/routes.rb
DaticalDb::Application.routes.draw do
  
  resources :jobs

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home/index"
    
  get "projects/show"
  get "projects/show_change_set"
  get "projects/show_history"
  get "projects/show_report"
  get "projects/show_snapshot"
  get "projects/exec_snapshot"
  
  resources :projects
  resources :users
  root 'home#index'

  

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :name, presence: true
  validates :command, presence: true
  validates :status, presence: true
  validates :notify, presence: true
  validates :user_id, presence: true
  
  belongs_to :user
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include JobsHelper
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    #@jobs = Job.all
    @jobs = Job.order(params[:sort])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    minute        = params[:iminute]['value']
    hour          = params[:ihour]['value']
    dayofmonth    = params[:idayofmonth]['value']
    month         = params[:imonth]['value']
    dayofweek     = params[:idayofweek]['value']
    pattern = minute + " " + hour + " " + dayofmonth + " " + month + " " + dayofweek

    @job.timepattern = pattern
    this_job = CronJob.new(pattern)
    next_comming_time = this_job.next(Time.now)
    @job.nextrun = next_comming_time
    
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :command, :timepattern, :status, :notify, :user_id)
    end
    
end

app/helpers/jobs_helper.rb
module JobsHelper
  
  STATUS      = {'Ready' => 1, 'Hold' => 2, 'Running' => 3, 'Service' => 4}
  
  NOTIFY = {'Pass' => 1, 'Fail' => 2, 'Warn' => 3, 'Always' => 4}
  
  
  def get_NotifyWhen(notify)
    notify_when = NOTIFY.index(notify)
  end
    
  def get_UserLogin(user_id)
    @user = User.find_by_id(user_id)
    @user.user_login
  end
  
  def get_Nextrun(time)
    time.ctime
  end
  
  def get_JobStatusText(job_status)
    status = STATUS.index(job_status)
    if status == "Ready"
      "<span class='label label-success'>#{status}</span>"
    elsif status == "Hold"
      "<span class='label label-important'>#{status}</span>"
    elsif status == "Service"
      "<span class='label label-warning'>#{status}</span>"
    end
  end
  
  private
  
  require 'set'
  require 'date'

  #
  # Parses cron expressions and computes the next & last occurence of the "job"
  #
  
  class CronJob
    # internal "mutable" time representation
    class InternalTime
      attr_accessor :year, :month, :day, :hour, :min
      attr_accessor :time_source
  
      def initialize(time,time_source = Time)
        @year = time.year
        @month = time.month
        @day = time.day
        @hour = time.hour
        @min = time.min
  
        @time_source = time_source
      end
  
      def to_time
        time_source.local(@year, @month, @day, @hour, @min, 0)
      end
  
      def inspect
        [year, month, day, hour, min].inspect
      end
    end
  
    SYMBOLS = {
       "jan" => "1",
       "feb" => "2",
       "mar" => "3",
       "apr" => "4",
       "may" => "5",
       "jun" => "6",
       "jul" => "7",
       "aug" => "8",
       "sep" => "9",
       "oct" => "10",
       "nov" => "11",
       "dec" => "12",
  
       "sun" => "0",
       "mon" => "1",
       "tue" => "2",
       "wed" => "3",
       "thu" => "4",
       "fri" => "5",
       "sat" => "6"
    }
  
    def initialize(source,time_source = Time)
      @source = source
      @time_source = time_source
      validate_source
    end
  
    ##########################
    # returns the next occurence after the given date
    ##########################

    def next(now = @time_source.now)
      t = InternalTime.new(now,@time_source)
  
      unless time_specs[:month][0].include?(t.month)
        nudge_month(t)
        t.day = 0
      end
  
      unless interpolate_weekdays(t.year, t.month)[0].include?(t.day)
        nudge_date(t)
        t.hour = -1
      end
  
      unless time_specs[:hour][0].include?(t.hour)
        nudge_hour(t)
        t.min = -1
      end
  
      # always nudge the minute
      nudge_minute(t)
      t.to_time
    end
  
    ##########################
    # returns the last occurence before the given date
    ##########################

    def last(now = @time_source.now)
      t = InternalTime.new(now,@time_source)
  
      unless time_specs[:month][0].include?(t.month)
        nudge_month(t, :last)
        t.day = 32
      end
  
      if t.day == 32 || !interpolate_weekdays(t.year, t.month)[0].include?(t.day)
        nudge_date(t, :last)
        t.hour = 24
      end
  
      unless time_specs[:hour][0].include?(t.hour)
        nudge_hour(t, :last)
        t.min = 60
      end
  
      # always nudge the minute
      nudge_minute(t, :last)
      t.to_time
    end
  
    SUBELEMENT_REGEX = %r{^(\d+)(-(\d+)(/(\d+))?)?$}
    def parse_element(elem, allowed_range)
      values = elem.split(',').map do |subel|
        if subel =~ /^\*/
          step = subel.length > 1 ? subel[2..-1].to_i : 1
          stepped_range(allowed_range, step)
        else
          if SUBELEMENT_REGEX === subel
            if $5 # with range
              stepped_range($1.to_i..$3.to_i, $5.to_i)
            elsif $3 # range without step
              stepped_range($1.to_i..$3.to_i, 1)
            else # just a numeric
              [$1.to_i]
            end
          else
            raise "Bad Vixie-style specification #{subel}"
          end
        end
      end.flatten.sort
  
      [Set.new(values), values]
    end
  
    protected
  
    # returns a list of days which do both match time_spec[:dom] and time_spec[:dow]
    def interpolate_weekdays(year, month)
      @_interpolate_weekdays_cache ||= {}
      @_interpolate_weekdays_cache["#{year}-#{month}"] ||= interpolate_weekdays_without_cache(year, month)
    end
  
    def interpolate_weekdays_without_cache(year, month)
      t = Date.new(year, month, 1)
      valid_mday = time_specs[:dom][0]
      valid_wday = time_specs[:dow][0]
  
      result = []
      while t.month == month
        result << t.mday if valid_mday.include?(t.mday) && valid_wday.include?(t.wday)
        t = t.succ
      end
  
      [Set.new(result), result]
    end
  
    def nudge_year(t, dir = :next)
      t.year = t.year + (dir == :next ? 1 : -1)
    end
  
    def nudge_month(t, dir = :next)
      spec = time_specs[:month][1]
      next_value = find_best_next(t.month, spec, dir)
      t.month = next_value || (dir == :next ? spec.first : spec.last)
  
      nudge_year(t, dir) if next_value.nil?
  
      # we changed the month, so its likely that the date is incorrect now
      valid_days = interpolate_weekdays(t.year, t.month)[1]
      t.day = dir == :next ? valid_days.first : valid_days.last
    end
  
    def date_valid?(t, dir = :next)
      interpolate_weekdays(t.year, t.month)[0].include?(t.day)
    end
  
    def nudge_date(t, dir = :next, can_nudge_month = true)
      spec = interpolate_weekdays(t.year, t.month)[1]
      next_value = find_best_next(t.day, spec, dir)
      t.day = next_value || (dir == :next ? spec.first : spec.last)
  
      nudge_month(t, dir) if next_value.nil? && can_nudge_month
    end
  
    def nudge_hour(t, dir = :next)
      spec = time_specs[:hour][1]
      next_value = find_best_next(t.hour, spec, dir)
      t.hour = next_value || (dir == :next ? spec.first : spec.last)
  
      nudge_date(t, dir) if next_value.nil?
    end
  
    def nudge_minute(t, dir = :next)
      spec = time_specs[:minute][1]
      next_value = find_best_next(t.min, spec, dir)
      t.min = next_value || (dir == :next ? spec.first : spec.last)
  
      nudge_hour(t, dir) if next_value.nil?
    end
  
    def time_specs
      @time_specs ||= begin
        # tokens now contains the 5 fields
        tokens = substitute_parse_symbols(@source).split(/\s+/)
        {
          :minute => parse_element(tokens[0], 0..59), #minute
          :hour   => parse_element(tokens[1], 0..23), #hour
          :dom    => parse_element(tokens[2], 1..31), #DOM
          :month  => parse_element(tokens[3], 1..12), #mon
          :dow    => parse_element(tokens[4], 0..6)  #DOW
        }
      end
    end
  
    def substitute_parse_symbols(str)
      SYMBOLS.inject(str.downcase) do |s, (symbol, replacement)|
        s.gsub(symbol, replacement)
      end
    end
  
  
    def stepped_range(rng, step = 1)
      len = rng.last - rng.first
  
      num = len.div(step)
      result = (0..num).map { |i| rng.first + step * i }
  
      result.pop if result[-1] == rng.last and rng.exclude_end?
      result
    end
  
    # returns the smallest element from allowed which is greater than current
    # returns nil if no matching value was found
    def find_best_next(current, allowed, dir)
      if dir == :next
        allowed.sort.find { |val| val > current }
      else
        allowed.sort.reverse.find { |val| val < current }
      end
    end
  
    def validate_source
      unless @source.respond_to?(:split)
        raise ArgumentError, 'not a valid cronline'
      end
      source_length = @source.split(/\s+/).length
      unless source_length >= 5 && source_length <= 6
        raise ArgumentError, 'not a valid cronline'
      end
    end
    
  end
  
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="container-fluid center">
    <div class="jobs form">
      <div class="row well" style="vertical-align: middle;">

        <div class="container">
          
          <div class="row">
            <div class="span2"><%= f.label :name %></div>
            <div class="span10"><%= f.text_field :name %></div>
          </div>
          
          <div class="row">
            <div class="span2"><%= f.label :command %></div>
            <div class="span10"><%= f.text_field :command %></div>
          </div>
          
          <div class="row">
            <div class="span2">Minute</div>
            <div class="span10">
                <%= select( "iminute", "value", {
                                  "Every" => "*",
                                   "*/5" => "*/5",
                                   "*/10" => "*/10",
                                   "*/15" => "*/15",
                                   "*/30" => "*/30"}) %>
              </div>
          </div>
          
          <div class="row">
            <div class="span2">Hour</div>
            <div class="span10">
                <%= select( "ihour", "value", {
                                    'Every' => '*',
                                    '0' => '0',
                                    '1' => '1',
                                    '2' => '2',
                                    '3' => '3',
                                    '4' => '4',
                                    '5' => '5',
                                    '6' => '6',
                                    '7' => '7',
                                    '8' => '8',
                                    '9' => '9',
                                    '10' => '10',
                                    '11' => '11',
                                    '12' => '12',
                                    '13' => '13',
                                    '14' => '14',
                                    '15' => '15',
                                    '16' => '16',
                                    '17' => '17',
                                    '18' => '18',
                                    '19' => '19',
                                    '20' => '20',
                                    '21' => '21',
                                    '22' => '22',
                                    '23' => '23'}) %>
              </div>
          </div>
          
          <div class="row">
            <div class="span2">Day of Month</div>
            <div class="span10">
                <%= select( "idayofmonth", "value", {
                                    "Every" => "*",
                                    '1' => '1',
                                    '2' => '2',
                                    '3' => '3',
                                    '4' => '4',
                                    '5' => '5',
                                    '6' => '6',
                                    '7' => '7',
                                    '8' => '8',
                                    '9' => '9',
                                    '10' => '10',
                                    '11' => '11',
                                    '12' => '12',
                                    '13' => '13',
                                    '14' => '14',
                                    '15' => '15',
                                    '16' => '16',
                                    '17' => '17',
                                    '18' => '18',
                                    '19' => '19',
                                    '20' => '20',
                                    '21' => '21',
                                    '22' => '22',
                                    '23' => '23',
                                    '24' => '24',
                                    '25' => '25',
                                    '26' => '26',
                                    '27' => '27',
                                    '28' => '28',
                                    '29' => '29',
                                    '30' => '30',
                                    '31' => '31'}) %>
              </div>
          </div>
          
          <div class="row">
            <div class="span2">Month</div>
            <div class="span10">
                <%= select( "imonth", "value", {
                            'Every'     => '*',
                            'January'   => '1',
                            'February'  => '2',
                            'March'     => '3',
                            'April'     => '4',
                            'May'       => '5',
                            'June'      => '6',
                            'July'      => '7',
                            'August'    => '8',
                            'September' => '9',
                            'October'   => '10',
                            'November'  => '11',
                            'December'  => '12'}) %>
              </div>
          </div>
          
          <div class="row">
            <div class="span2">Day of Week</div>
            <div class="span10">
                <%= select( "idayofweek", "value", {
                            'Every'       => '*',
                            'Sunday'      => '0',
                            'Monday'      => '1',
                            'Tuesday'     => '2',
                            'Wednesday'   => '3',
                            'Thursday'    => '4',
                            'Friday'      => '5',
                            'Saturday'    => '6'}) %>
              </div>
          </div>
          
          <div class="row">
            <div class="span2"><%= f.label :status %></div>
            <div class="span10"><%= f.select(:status, JobsHelper::STATUS) %></div>
          </div>
          
           <div class="row">
            <div class="span2"><%= f.label :notify, t('.notify_when') %></div>
            <div class="span10"><%= f.select(:notify, JobsHelper::NOTIFY) %></div>
          </div>
          
          <div class="row">
            <div class="span2"><%= f.label :user, t('.notify_user') %></div>
            <div class="span10"><%= collection_select :job, :user_id, User.find(:all), :id, :user_login %></div>
          </div>
          
        </div>
        
        <div class="actions">
          <%= f.submit %>
        </div>
        
      </div>
    </div>
  </div>
  
  
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class="container-fluid center">
  
  <div class="span9">
  <br/>
  <fieldset>
    <legend><h3><%= t('.title_sched_jobs') %></h3></legend>
  </fieldset>
  </div>
  
  <div class="span3" style="text-align: right;">
    <br/><br/>
    <%= link_to t('.new_job'), new_job_path, :class => "btn btn-success btn-mini" %>
  </div>

  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
  
  <table class="table table-hover table-bordered table-condensed table-striped">
    <thead>
      <tr>
        <th><%= link_to t('.name'), :sort => "name" %></th>
        <th><%= link_to t('.command'), :sort => "command" %></th>
        <th><%= link_to t('.timepattern'), :sort => "timepattern" %></th>
        <th><%= link_to t('.nextrun'), :sort => "nextrun" %></th>
        <th style="text-align: center;"><%= link_to t('.status'), :sort => "status" %></th>
        <th style="text-align: center;"><%= t('.notify_when') %></th>
        <th><%= t('.notify_user') %></th>
        <th colspan=3 style="text-align: center;"><%= t('.actions') %></th>
      </tr>
    </thead>
  
    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.name %></td>
          <td><%= job.command %></td>
          <td><%= job.timepattern %></td>
          <td><%= get_Nextrun(job.nextrun) %></td>
          <td style="text-align: center;"><%= raw get_JobStatusText(job.status) %></td>
          <td style="text-align: center;"><%= get_NotifyWhen(job.notify) %></td>
          <td><%= get_UserLogin(job.user_id) %></td>
          <td colspan=3 style="text-align: center;">
            <%= link_to t('.Show'), job, :class => "btn btn-success btn-mini" %>
            <%= link_to 'Edit', edit_job_path(job), :class => "btn btn-success btn-mini" %>
            <%= link_to 'Destroy', job, method: :delete, :class => "btn btn-success btn-mini", data: { confirm: "Delete Job: #{job.name}?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
</div>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job.name %>
</p>

<p>
  <strong>Command:</strong>
  <%= @job.command %>
</p>

<p>
  <strong>Timepattern:</strong>
  <%= @job.timepattern %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job.status %>
</p>

<p>
  <strong>User:</strong>
  <%= get_UserLogin(@job.user_id) %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>