config/routes.rb
DaticalDb::Application.routes.draw do
  
  resources :jobs

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home/index"
    
  get "projects/show"
  get "projects/show_change_set"
  get "projects/show_history"
  get "projects/show_report"
  get "projects/show_snapshot"
  get "projects/exec_snapshot"
  
  resources :projects
  resources :users
  root 'home#index'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <center>
    <small>
      <%= image_tag( "copyright.png", :border => 0, :align => "top" ) %> <%= t('.copyright') %>
      <%= image_tag( "datical_logo.png", :border => 0, :align => "top" ) %>
    </small>
    </center>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <span class="brand" href="./index.html"><%= image_tag( "datical_hdr_logo.png", size: "22x22", :border => 0, :align => 'middle') %> <%= t('.company_name') %></span>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><%= link_to t('.home'),    root_url %></li>
          <li><%= link_to t('.help'),    '/help' %></li>
          <% if session[:user_login] == nil %>
            <li><%= link_to t('.login'), '/login' %></li>
          <% end %>
          <% if session[:user_login] != nil %>
            <li><%= link_to t('.logout'), '/logout' %></li>
            <li><%= link_to t('.login_as') + "#{session[:user_login]}", '' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav_sidebar.html.erb
<br/>
  
<% if session[:user_login] != nil %>
  
<div class='nav_sidebar_background'>
  
  <li class="nav-header"><%= t('.title_projects') %></li>
  <ul>
    <ul class="nav">
      <li><%= link_to image_tag( "database.png", :border => 0, :align => "top" ) + " " + t('.tab_db_projects'), projects_path %></li>
    </ul>
  </ul>
  
  <li class="nav-header"><%= t('.title_jobs') %></li>
  <ul>
    <ul class="nav">
      <li><%= link_to image_tag( "jobs_num.png", :border => 0, :align => "top" ) + " " + t('.tab_jobs'), jobs_path %></li>
      <li><%= link_to image_tag( "runs.png", :border => 0, :align => "top" ) + " " + t('.tab_runs'), jobs_path %></li>
    </ul>
  </ul>
  
  <li class="nav-header"><%= t('.title_users') %></li>
  <ul>
    <ul class="nav">
      <li><%= link_to image_tag( "users.png", :border => 0, :align => "top" ) + " " + t('.tab_users'), users_path %></li>
      <li><%= link_to image_tag( "roles.png", :border => 0, :align => "top" ) + " " + t('.tab_roles'), users_path %></li>
      <li><%= link_to image_tag( "creds.png", :border => 0, :align => "top" ) + " " + t('.tab_credentials'), users_path %></li>
      <br/>
    </ul>
  </ul>
  
</div>

<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= t('.app_name') %></title>
  <%= favicon_link_tag 'favicon.png' %>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>

<body>

  <div class="container-fluid">
    
    <%= render 'layouts/header' %>
    
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <%= render :partial => "layouts/nav_sidebar" %>
          <%= render 'layouts/footer' %>
        </div>
        <div class="span10">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  
</body>

</html>